gridsuite/griddyna-app

src/containers/MenuContainer.jsx
src/redux/slices/Mapping.js

Specificities attached to this particular case are handled servert-side, enabling a coherent experience (any renaming is persisted).

Process renaming of a new default mapping as any other renaming

---

.env
.env.development
public/idpSettings.json
src/rest/mappingsAPI.js
src/rest/scriptsAPI.js
src/setupProxy.js

Properly handles servers calls when using the gateway or not.

Fix Gateway calls when not using local server

---

Dockerfile
app-httpd.conf

Signed-off-by: Jon Harper <jon.harper87@gmail.com>

Switch to bitnami/apache base image because it is non root

---

src/components/1-atoms/Autocomplete.jsx
src/components/2-molecules/FilterBar.jsx
src/components/3-molecules/Filter.jsx
src/constants/equipmentDefinition.js
src/constants/operands.js
src/containers/FilterContainer.jsx
src/containers/MappingContainer.jsx
src/containers/MenuContainer.jsx
src/redux/slices/Mapping.js
src/utils/optionsBuilders.js

- Add Includes filter for String and Number
- Add shortened labels for nested properties in equipments
- Add rule filters to only show some of the rules

feat: Add includes filter for String and Number Values + various QoL improvements

---

src/components/1-atoms/buttons/index.jsx
src/components/2-molecules/BooleanOperatorSelect.jsx
src/components/3-molecules/FiltersGroup.jsx
src/components/3-molecules/FiltersGroupStyles.js
src/components/3-molecules/Rule.jsx
src/components/3-molecules/RuleStyle.js
src/containers/RuleContainer.jsx
src/redux/slices/InstanceModel.js
src/redux/slices/Mapping.js
src/utils/composition.js

- Addition of a new simpler way to display filter composition, hiding all boolean logic.
- Add warning when some filters are unused by the composition

Add a new display of filter composition

---

.github/workflows/build.yml

Signed-off-by: HARPER Jon <jon.harper87@gmail.com>

switch git branch master to main

---

src/utils/parameters.js

Signed-off-by: Gautier Bureau <gautier.bureau@rte-france.com>

Fix double regex for parameters and accept negative double.

---

.env
package-lock.json
package.json
src/components/app.js
src/redux/slices/User.js
src/setupProxy.js
src/utils/rest-api.js

Signed-off-by: sBouzols <sylvain.bouzols@gmail.com>

Manage unauthorized user connection alert

---

src/components/app.js

Signed-off-by: sBouzols <sylvain.bouzols@gmail.com>

Fix: Use the correct redux store slice for authenticationRouterError

---

src/components/1-atoms/Autocomplete.jsx
src/components/3-organisms/Filter.jsx
src/containers/FilterContainer.jsx

When select a value in filter => an exhaustive deep rendering happens

Selecting a value in filter gets an exhaustive deep rendering

---

src/components/2-molecules/Stepper.jsx
src/components/2-molecules/VerticalStepper.jsx
src/containers/ParametersContainer.jsx

Create/Editing Parameter dialogue actually using Back | Next to navigate parameter set => must provide a list to choose directly the parameter set.

Must provide a list to choose directly the parameter set in Create/Editing Parameter Group dialogue

---

package-lock.json
src/containers/FilterContainer.jsx
src/redux/selectorUtil.js
src/redux/slices/Mapping.js
src/redux/slices/Network.js

Matched equipements are not shown after select a value for a new created filter. This bug occurs only if not yet select model and group

Matched equipemets not shown after selecting a value in a newly added filter.

---

src/redux/slices/Mapping.js
src/redux/slices/Model.js
src/redux/slices/Network.js
src/redux/slices/Script.js
src/rest/mappingsAPI.js
src/rest/modelsAPI.js
src/rest/networkAPI.js
src/rest/scriptsAPI.js
src/utils/rest-api.js

Signed-off-by: Ayoub LABIDI <ayoub.labidi@protonmail.com>

Unify exception handling

---

package-lock.json
package.json
src/components/app.js

Signed-off-by: sBouzols <sylvain.bouzols@gmail.com>

Refactor move handle signin silent in commons UI

---

src/redux/slices/Model.js

Dynamic simulation - Do not show all models if type or family not selected

---

package-lock.json
package.json
src/components/app.js
src/rest/studyAPI.js
src/utils/rest-api.js

Following #81
Update dialog and use new API of gridsuite/study-server#494

Update "about" dialog

---

package-lock.json
package.json
src/components/app.js

We will have to wait the release of commons-ui with https://github.com/gridsuite/commons-ui/pull/330 to be efficient

fix(authentication): adapt code for authorization code flow with PKCE

---

.github/config/.licenserc.yaml
.github/workflows/build.yml
README.md
license-checker-config.json
package-lock.json
package.json
src/__mocks__/svgrMock.js
src/components/2-molecules/BooleanOperatorSelect.jsx
src/components/app.test.js
src/plugins/index.js
src/react-app-env.d.ts
src/redux/selectors.js
src/setupProxy.js

chore(): Add license-checker and licenses-check script action to avoid license breaking. Add the step in ci build to automatically check it before merging

Add license-checker

---

package.json
public/idpSettings.json

Dependents with https://github.com/gridsuite/deployment/pull/401

Update dev server port to 3003

---

package-lock.json
package.json
src/components/3-organisms/Filter.jsx

This PR FIX also expert filter does not take 100% of parent width

Upgrade to commons-ui v0.68.4

---

.github/workflows/build.yml
package-lock.json
package.json

Related to powsybl/github-ci#14

Upgrade to node 22

---

package-lock.json
package.json

Upgrade react-intl

---

package-lock.json
package.json

Apply comons-ui patch for esbuild

---

Dockerfile

Fix Dockerfile for Vite migration

---

package.json

Start maintaining version package.json in main

main package version

---

Dockerfile

`sed` must be exact in `Dockerfile`

---

package-lock.json
package.json
src/components/3-organisms/Filter.jsx
src/constants/expertFilter.ts

Require : https://github.com/gridsuite/commons-ui/pull/535

Customize expert filter with P, Q, P Absolute, Q Absolute for Generator
